### ISSUE TITLE
Problem: Calling blacklisted functions always aborts

### ISSUE THREAD

**Issue by lukego** [raptorjit/raptorjit#119]
When recording a trace, calling a function that has already been blacklisted will always cause an abort (#118). This is a problem because sometimes a blacklisted function could actually be traced successfully if only we actually tried. This means that the JIT is being too liberal in allowing blacklisting marks to propagate, contrary to the goal of blacklisting very conservatively (#100).

Consider this example function:

```lua
function sizeof_int32 ()
   return ffi.sizeof('int32_t')
end
```

If you try to compile this function in isolation, with a trace starting at the function head, then it will abort and eventually be blacklisted. The reason is obscure: the trace ends in a call to a C library function, that call is a tail-call, and the tail-call is made at the same stack depth where the trace started. This is a corner case that the JIT does not support and it leads to the infamous `leaving loop in root trace` abort message. (If anybody knows why that particular message is chosen here then please pipe up :-)).

Now consider some other code that calls this function:

```lua
for i = 1, 100 do
   sizeof_int32()
end
```

This can actually compile perfectly fine with a trace starting on the `for` loop and the call being inlined. The reason is that it does not exercise the specific corner case that causes a problem when the trace is compiled in isolation. Specifically, when the loop calls the function `sizeof_int32()` this increases the stack depth in the trace, and this means that the tail-call to `ffi.sizeof()` is no longer happening at the same stack depth where the trace started, and this means that we miss the corner case and the JIT produces a successful recording.

Clear as mud?

So now it might seem like compiling `sizeof_int32()` in isolation will fail but we shouldn't care because when another trace calls this function it can still successfully record an inline version of the call. Performance should be fine because in practice the actual function calls will be inlined and traced.

However, this does not necessarily happen in practice. If this function is blacklisted by the JIT then _it will no longer attempt to record calls to the function at all_ (#118). So the blacklisting mark at the function head will actually prevent any code that calls `sizeof_uint32()` from being compiled, even when it would have succeeded, and this eventually makes the blacklisting propagate far and wide throughout the codebase.

This is a bug. The JIT needs to be very conservative about allowing blacklistings to propagate (#100). It should handle the reality that certain functions fail to JIT in isolation but can still be inlined into successful traces.

**Comment by szbnwer** [comment]
hi there!

im just learning, so i can say any kinda deep bullshit, i didnt even try raptorjit so far, but one day i wanna become a professional around lua luajit and cool stuffs around just like raptorjit :)

so i have a small idea to make blacklisting contextual, so its fine to blacklist something on one place then next time next place can have a new chance. this can have a bigger overhead if theres no data recorded for this purpose already, and it can be hard to distinguish between differences, so i mean jit is about make faster alternative paths than the additional calculations, but this all depends on the cost of possibly much retry...

ps: many thx 4 ur work, i can see its values and ive learnt from your researches much :)

**Comment by szbnwer** [comment]
sorry for the noise, ive read this first and then found the related pull request...
