### ISSUE TITLE
Clear blacklisting state on jit.flush()

### ISSUE THREAD

**Issue by lukego** [raptorjit/raptorjit#125]
Blacklistings should be cleared when the JIT flushes. This is especially important because often JIT flushes are performed specifically with the intention of clearing unwanted JIT state such as blacklisting marks.

One simple implementation strategy would be to iterate through all functions (`GCproto` objects) and replace every ILOOP/IFUNC/... bytecode with LOOP/FUNC/... to restore the original state. This may require defining a way to iterate through all prototypes but this should not be especially performance sensitive since JIT flush is already fairly drastic.

See also https://github.com/LuaJIT/LuaJIT/issues/232.

**Comment by fogfx** [comment]
FWIW I believe `jit.on()` clears blacklisting.

**Comment by lukego** [comment]
Thanks for pointing that out @fogfx!

@alexandergall has actually fixed this issue privately and I am going to cherry-pick his solution soon. He made `jit.flush()` walk the full heap and apply the unblacklisting logic of `jit.on()` to each function that has a blacklisted bytecode. He says it is working well.

@alexandergall Could you link to that commit so that I can grab it please? :-)

**Comment by alexandergall** [comment]
https://github.com/alexandergall/snabbswitch/commit/8beb311332a6c95ab1d2934f292f41563b878edb
