### ISSUE TITLE
`nix-shell` produces an error when invoked as suggested

### ISSUE THREAD

**Issue by tom-seddon** [raptorjit/raptorjit#158]
The README suggests typing `nix-shell` to open a shell with the build environment set up. But  when I try this, I get an error:

```
vagrant@ubuntu-xenial:~/raptorjit$ nix-shell
error: nix-shell requires a single derivation
Try 'nix-shell --help' for more information.
```

Thanks,

--Tom

**Comment by lukego** [comment]
Thanks for reporting! Fixed now.

Sorry about the slow reply. Just following too many repos on Github nowadays and missing some important notifications in all the noise.
