### ISSUE TITLE
Raptorjit leaks tons of memory running the fasta benchmark

### ISSUE THREAD

**Issue by fsfod** [raptorjit/raptorjit#181]
When our modified version of the [fasta benchmark ](https://github.com/softdevteam/lua_benchmarking/blob/master/benchmarks/fasta/bench.lua) is run under RaptorJIT it just ends leaking tons of memory. In previous versions of Raptorjit this never happened and doesn't happen with normal LuaJIT or GC64 builds.

**Comment by lukego** [comment]
Thanks for the report. I've reproduced this and I'm running a `git bisect` to see where this behaviour appeared.

It's the first time I've seen the VM allocating 60GB+ heaps in `top` :)

**Comment by lukego** [comment]
The `git bisect` traced this to the introduction of `T->szirmcode` i.e. the table keeping track of how many bytes of machine code were assembled for each IR instruction. I made a seemingly obvious fix there in #183 but now I'm seeing a segfault on this `fasta` benchmark. I'm looking into that now.

**Comment by lukego** [comment]
@fsfod Does #183 resolve this for you? (not merged onto master yet.)

**Comment by fsfod** [comment]
Yes it does.

**Comment by lukego** [comment]
Thanks for the report & testing!
