### ISSUE TITLE
Linking with libraptorjit

### ISSUE THREAD

**Issue by lazara5** [raptorjit/raptorjit#216]
I am trying to dynamically link an application with libraptorjit (built on CentOS 7.6, gcc 7.3.1). The problem is that libraptorjit.so has a dependency on lj_dwarf_dwo_dyn.o, which does not seem to be an actual shared library. What is the proper way to handle this dependency? 
Additionally, is there any reason why raptorjit no longer installs a pkg-config file ?

**Comment by lukego** [comment]
> I am trying to dynamically link an application with libraptorjit (built on CentOS 7.6, gcc 7.3.1)

Sorry about the hiccups. Tests currently only cover static linking. Fixing.

> The problem is that libraptorjit.so has a dependency on lj_dwarf_dwo_dyn.o

Can you check whether #217 fixes this problem by removing that dependency?

> is there any reason why raptorjit no longer installs a pkg-config file ?

No, not specifically. If this is useful to you then please re-add it and PR that. I have only taken a hack-and-slash approach to trying to make the Makefile shorter and simpler and there has surely been some collateral damage (and it's still quite long even now...)

**Comment by lukego** [comment]
Thanks for confirming. I'll push a minor maintenance release for this library fix. If you send in the pkg-config fix I can push that as a maint release later too.
